### ISSUE TITLE
PolygonCutOut crashes on startup and prevents JOSM from starting

### ISSUE THREAD

**Issue by SlowMo24** [bdxd111/JOSM-Polygon-Cut-Out#5]
Hey,

thanks for your work on this great plugin.

This plugin crashes on Version 18622 of JOSM and prevents it from starting. The stack trace suggest this is due to the JVM-version used when compiling. You can see all information here: https://josm.openstreetmap.de/ticket/22653

**Comment by bdxd111** [comment]
I have recompiled it now with java 8 so it should now be compatible. I think that is the minimum java version supported by JOSM itself.

To fix the issue, I think you have to manually delete the plugin file to get JOSM to start. See [https://wiki.openstreetmap.org/wiki/JOSM/Plugins](https://wiki.openstreetmap.org/wiki/JOSM/Plugins#:~:text=Manually%20install%20JOSM%20plugins). Then you can reinstall the plugin like normal.

**Comment by SlowMo24** [comment]
thanks, its fixed
